services:
    backend:
        container_name: backend
        build: ./backend
        ports: 
            - 5051:4000
        command: npm run dev
        volumes: 
            - ./backend/src/:/app/src/
    frontend: 
        container_name: frontend
        build: ./frontend
        ports:
            - 8081:5173
        command: npm run dev
        volumes: 
            - ./frontend/src/:/app/src/
