services:
    backend:
        container_name: backend
        build: ./backend
        volumes: 
            - ./backend/src/:/app/src/
        environment:
            DB_PASSWORD: ${DB_PASSWORD}
            DB_SCHEMA: ${DB_SCHEMA}
            DB_USER: ${DB_USER}
            DB_HOST: ${DB_HOST}
    frontend: 
        container_name: frontend
        build: ./frontend
        volumes: 
            - ./frontend/src/:/app/src/
        environment: 
            VITE_GATEWAY_PORT: ${GATEWAY_PORT}
    database:
        container_name: database
        image: postgres
        volumes: 
            - ./persist/data/:/var/lib/postgresql/data/
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_SCHEMA}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_HOST: ${DB_HOST}
    vizualizer:
        container_name: vizualizer
        image: adminer
    gateway:
        container_name: gateway
        image: nginx
        ports:
            - ${GATEWAY_PORT}:80
        volumes: 
            - ./nginx.dev.conf:/etc/nginx/nginx.conf
        

